### ISSUE TITLE
Worry about  a warning of numpy

### ISSUE THREAD

**Issue by SEU-zxj** [OpenDriveLab/Vista#47]
Hi @Little-Podi 
Thanks for your great  #work❤!
Everytime I try to run the train command (e.g. the command you provided in document `python train.py --base configs/example/nusc_train.yaml --num_nodes 1 --n_devices 1`), the system will give me a warning like this:
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

The Traceback is as follows:
```
Traceback (most recent call last):  
......
......
  File "/DATA_EDS/zhengxj/anaconda3/envs/vista/lib/python3.11/site-packages/torchmetrics/functional/text/__init__.py", line 17, in <module>
    from torchmetrics.functional.text.chrf import chrf_score
  File "/DATA_EDS/zhengxj/anaconda3/envs/vista/lib/python3.11/site-packages/torchmetrics/functional/text/chrf.py", line 33, in <module>
    _EPS_SMOOTHING = tensor(1e-16)
/DATA_EDS/zhengxj/anaconda3/envs/vista/lib/python3.11/site-packages/torchmetrics/functional/text/chrf.py:33: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /opt/conda/conda-bld/pytorch_1682343995622/work/torch/csrc/utils/tensor_numpy.cpp:84.)
```
I wonder this warning is OK? Will it affect to the process of training?

**Comment by SEU-zxj** [comment]
Hello, I found that in your `requirements.txt`, you set the `numpy`>1.24.4.
https://github.com/OpenDriveLab/Vista/blob/6ff19b805c646e050414567425728aac4257d767/requirements.txt#L16
So, my conda install a version of 2.0.1.

And if I run the reference code `python sample.py`, I will finally get an error:
```
Traceback (most recent call last):
  File "/DATA_EDS/zhengxj/projects/cognitive-driving-world-model/Vista/sample.py", line 224, in <module>
    img = load_img(each_path, opt.height, opt.width)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/DATA_EDS/zhengxj/projects/cognitive-driving-world-model/Vista/sample.py", line 197, in load_img
    image = transforms.Compose([
            ^^^^^^^^^^^^^^^^^^^^
  File "/DATA_EDS/zhengxj/anaconda3/envs/vista/lib/python3.11/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
          ^^^^^^
  File "/DATA_EDS/zhengxj/anaconda3/envs/vista/lib/python3.11/site-packages/torchvision/transforms/transforms.py", line 137, in __call__
    return F.to_tensor(pic)
           ^^^^^^^^^^^^^^^^
  File "/DATA_EDS/zhengxj/anaconda3/envs/vista/lib/python3.11/site-packages/torchvision/transforms/functional.py", line 166, in to_tensor
    img = torch.from_numpy(np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Numpy is not available
```

And I tried to down grade the `numpy` version from 2.0.1 to 1.24.4.

And I can solve this problrm.

**Comment by SEU-zxj** [comment]
So, maybe we should change the “>=” to "==" below?
https://github.com/OpenDriveLab/Vista/blob/6ff19b805c646e050414567425728aac4257d767/requirements.txt#L16

**Comment by SEU-zxj** [comment]
As my question solved, I will close this issue~
